### ISSUE TITLE
Datenquellen überarbeiten: Infos sorgfältig angeben

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/IM1#11]

**Comment by benjbk** [comment]
Habe soweit alle Kontaktinfos ergänzt und versucht, den Datenbestand der Inis darzustellen. Im Grunde kann man damit loslegen, auch wenn die Darstellung der Tabelle im Wordpress immer noch grausig ist. Es gibt leider nicht für alle Wilkommensbündnisse usw. einen Telefonkontakt.
