### ISSUE TITLE
Gemeindedolmetscherdienst wegen Preismodell recherchieren

### ISSUE THREAD

**Issue by felixkamille** [AfeefaDe/IM1#8]

**Comment by ahmadmu** [comment]
Online rechechiert: Eine Normzeile enthält 50-55 Zeichen (mit leerzeichen), und pro Zeile liegt der Preis zwischen 0,50 und 3-4€ je nach komplexität und fachspezifität, nach § 11 JVEG wird 1,55€ vorgeschlagen aber das wird meistens bei beglaubigte translation gefragt, bei uns klingt 0,50-0,60€ am realistischsten gut meiner meinung nach, mit unser neuen Zeichenlimit und wenn wir höhstens 7 Zeileneinträge übersetzen, dann wird maximal pro Eintrag 3,5-4€  gefragt (5€ bei ältere  Einträge die gut geschrieben sind, wir können vllt eine Grenze von 5€ machen), also maximal werden wir für Persisch und Russisch 4x400x2= 3600€ (5x400x2 = 4000€) ausgeben, ein realistischeres maximal ist so 2500-2800€ würde ich sagen, wenn wir die 0,50€ pro Zeile nehmen.
